### ISSUE TITLE
Different API Syncing Issues

### ISSUE THREAD

**Issue by ethanleifer** [secretanalytics/sn-mono#10]
Each API is synced from a few different starting heights: 

Do API Responses differ if the starting height is different? How do we account for this?

**Comment by ethanleifer** [comment]
https://discord.com/channels/@me/1067474889314930759/1079245373056491571

**Comment by zackgow** [comment]
One approach is to query the minimum block height of each endpoint and then just use the lowest block height that is returned.

**Comment by ethanleifer** [comment]
Is there a reliable way to query min block height with LCD?
