### ISSUE TITLE
Get rid of on conflict DO NOTHING and update triggers for cases

### ISSUE THREAD

**Issue by ethanleifer** [secretanalytics/sn-mono#5]
update case for triggers (what about deleting?)

**Comment by zackgow** [comment]
Keeping DO NOTHING is fine, but we wouldn't be updating anything in that row right? Essentially it would be if duplicate data somehow got in?

**Comment by ethanleifer** [comment]
If we want updates to work, we would just have to update txs, raw_txs in trigger. Then delete the logs and retrigger the python code for that transaction.

Its not that complicated
